# site settings
title: Shuta Suzuki
subtitle:
email: shutas (at) umich.edu
description: Personal website of Shuta Suzuki
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 615 South Main Street
city: Ann Arbor
state: MI
zip_code: 48104
country: United States of America
phone: +1 (248) 860-0866

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url: https://www.facebook.com/afdashuta
github_url: https://github.com/shutas
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/shuta-suzuki
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

# Copy Over Assets Directory
  include: ['assets']
