# site settings
title: Shuta Suzuki
subtitle:
email: shutas@umich.edu
description: Personal website for Shuta Suzuki
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 57421 Windmill Pointe
city: New Hudson
state: MI
zip_code: 48165
country: United States of America
phone: (248) 860-0866

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6 # This was originally 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/afdashuta
github_url: https://github.com/shutas
gitlab_url: https://gitlab.eecs.umich.edu/shutas
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/shuta-suzuki-b445a2bb
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

# Copy Over Assets Directory
  include: ['assets']