# site settings
title: Shuta
subtitle: Suzuki
email: shutas@umich.edu
description: Personal website for Shuta Suzuki
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://shutas.netlify.com # the base hostname & protocol for your site
author:
street_address: 57421 Windmill Pointe
city: New Hudson
state: MI
zip_code: 48165
country: United States of America
phone: (248) 860-0866

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
